-- CreateTable
CREATE TABLE "reach"."file_share_file" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "share_id" DECIMAL(20,0) NOT NULL,
    "is_uploaded" BOOLEAN NOT NULL DEFAULT false,
    "compressed_size" INTEGER NOT NULL,
    "unique_id" DECIMAL(20,0),
    "file_type" SMALLINT,
    "megalo_category_index" SMALLINT,
    "size_in_bytes" DECIMAL(20,0),
    "activity" SMALLINT,
    "game_mode" SMALLINT,
    "game_engine_type" INTEGER,
    "map_id" INTEGER,
    "created_at" TIMESTAMP(6),
    "creator_xuid" DECIMAL(20,0),
    "creator_name" VARCHAR(16),
    "creator_is_xuid_online" BOOLEAN,
    "modified_at" TIMESTAMP(6),
    "modifier_xuid" DECIMAL(20,0),
    "modifier_name" VARCHAR(16),
    "modifier_is_xuid_online" BOOLEAN,
    "name" VARCHAR(128),
    "description" VARCHAR(128),
    "icon_index" SMALLINT,
    "length_seconds" INTEGER,
    "hopper_identifier" INTEGER,
    "campaign_id" INTEGER,
    "campaign_difficulty" INTEGER,
    "campaign_metagame_scoring" INTEGER,
    "campaign_insertion_point" INTEGER,
    "campaign_primary_skulls" INTEGER,
    "campaign_secondary_skulls" INTEGER,
    "firefight_difficulty" INTEGER,
    "firefight_primary_skulls" INTEGER,
    "firefight_secondary_skulls" INTEGER,

    CONSTRAINT "file_share_file_pkey" PRIMARY KEY ("id")
);
