export enum HaloReachBountyChallenge {
    any_100_kill_bounty = 0,
    any_50_kill_bounty = 1,
    any_25_kill_bounty = 2,
    mp_100_kill_bounty = 3,
    mp_50_kill_bounty = 4,
    mp_25_kill_bounty = 5,
    mp_50_assists_bounty = 6,
    mp_30_assists_bounty = 7,
    mp_20_assists_bounty = 8,
    mp_10_assists_bounty = 9,
    ff_100_kill_bounty = 10,
    ff_75_kill_bounty = 11,
    ff_50_kill_bounty = 12,
    ff_50_assists_bounty = 13,
    ff_30_assists_bounty = 14,
    ff_20_assists_bounty = 15,
}

export enum HaloReachWeeklyChallenge {
    _30k_chall = 0,
    mp_spree_4x_chall_week = 1,
    _1500k_week_chall = 2,
    win_50_mm_games = 3,
    win_77_mm_games = 4,
    m10_slaso = 5,
    m20_slaso = 6,
    m30_slaso = 7,
    m35_slaso = 8,
    m45_slaso = 9,
    m50_slaso = 10,
    m52_slaso = 11,
    m60_slaso = 12,
    m70_slaso = 13,
    weekly_open_nat_chall = 14,
    weekly_multikill_chall = 15,
    weekly_revenge_chall = 16,
    weekly_precision_chall = 17,
    play_x_mm_games = 18,
    m20_time_black_eye_chall = 19,
    endure_chall = 20,
    complete_all_daily_chall = 21,
    complete_x_daily_chall = 22,
    m30_sniper_weekly = 23,
    survival_round_weekly = 24,
    survival_wave_weekly = 25,
    legend_coop_weekly = 26,
    heroic_mission_weekly = 27,
    firebird_weekly_chall = 28,
    camp_any_speed_run = 29,
    camp_high_score = 30,
    legend_speed_solo_desc = 31,
    temp_w_2 = 32,
    temp_w_3 = 33,
    temp_w_4 = 34,
    temp_w_5 = 35,
    temp_w_6 = 36,
    temp_w_7 = 37,
}

export enum HaloReachCampaignChallenge {
    mythic_chall = 0,
    tough_luck_chall = 1,
    catch_chall = 2,
    iron_solo_chall = 3,
    famine_chall = 4,
    thunderstorm_chall = 5,
    iron_coop_chall = 6,
    tilt_chall = 7,
    mythic_luck_chall = 8,
    mythic_storm_chall = 9,
    mythic_tilt_storm_chall = 10,
    storm_famine_tilt_chall = 11,
    fog_catch_luck_chall = 12,
    famine_luck_storm_chall = 13,
    fog_famine_chall = 14,
    mythic_tilt_storm_luck_chall = 15,
    m10_l_deathless = 16,
    m20_l_deathless = 17,
    m30_l_deathless = 18,
    m35_l_deathless = 19,
    m45_l_deathless = 20,
    m50_l_deathless = 21,
    m52_l_deathless = 22,
    m60_l_deathless = 23,
    m70_l_deathless = 24,
    any_score_easy_chall = 25,
    m10_l_deathless_skull = 26,
    m20_l_deathless_skull = 27,
    m30_l_deathless_skull = 28,
    m35_l_deathless_skull = 29,
    m45_l_deathless_skull = 30,
    m50_l_deathless_skull = 31,
    m52_l_deathless_skull = 32,
    m60_l_deathless_skull = 33,
    m70_l_deathless_skull = 34,
    elite_kill_chall = 35,
    grunt_kill_chall = 36,
    any_speed_chall = 37,
    camp_precision_chall = 38,
    camp_auto_chall = 39,
    camp_leader_chall = 40,
    camp_infantry_chall = 41,
    m45_elite_pod_chall = 42,
    single_skull_chall = 43,
    special_elite_heroic = 44,
    special_elite_normal = 45,
    m30_sniper_chall = 46,
    m30_sniper_med_chall = 47,
    m20_airstrike_chall = 48,
    m50_firebird_chall = 49,
    fauna_kill_chall = 50,
    score_constrained = 51,
    score_deathless = 52,
    special_elite_m52 = 53,
    temp_c_5 = 54,
}

export enum HaloReachFirefightChallenge {
    ff_kill_spree_chall = 0,
    ff_kill_spree_5_chall = 1,
    ff_h_kill_spree_10_chall = 2,
    ff_multikill_7_chall = 3,
    ff_h_multikill_7_chall = 4,
    ff_grunt_kill_chall = 5,
    ff_elite_kill_chall = 6,
    ff_h_elite_kill_chall = 7,
    ff_headshot_kill_chall = 8,
    ff_launcher_kill_chall = 9,
    ff_shotgun_kill_chall = 10,
    ff_precision_kill_chall = 11,
    ff_grenade_kill_chall = 12,
    ff_pistol_chall = 13,
    ff_supercombine_kill_chall = 14,
    ff_sword_kill_chall = 15,
    ff_overlook_kill_chall = 16,
    ff_h_overlook_kill_chall = 17,
    ff_l_overlook_kill_chall = 18,
    ff_courtyard_kill_chall = 19,
    ff_h_courtyard_kill_chall = 20,
    ff_l_courtyard_kill_chall = 21,
    ff_corvette_kill_chall = 22,
    ff_h_corvette_kill_chall = 23,
    ff_l_corvette_kill_chall = 24,
    ff_holdout_kill_chall = 25,
    ff_h_holdout_kill_chall = 26,
    ff_l_holdout_kill_chall = 27,
    ff_icecave_kill_chall = 28,
    ff_h_icecave_kill_chall = 29,
    ff_l_icecave_kill_chall = 30,
    ff_park_kill_chall = 31,
    ff_h_park_kill_chall = 32,
    ff_l_park_kill_chall = 33,
    ff_ruins_kill_chall = 34,
    ff_h_ruins_kill_chall = 35,
    ff_l_ruins_kill_chall = 36,
    ff_easy_score_chall = 37,
    ff_deathless_game_chall = 38,
    ff_5_deaths_chall = 39,
    ff_waterfront_kill_chall = 40,
    ff_h_waterfront_kill_chall = 41,
    ff_l_waterfront_kill_chall = 42,
    kill_attack_chall = 43,
    kill_h_attack_chall = 44,
    vehicle_killing_chall = 45,
    ff_airstrike_chall = 46,
    ff_deathless_round = 47,
    ff_deathless_rounds = 48,
    ff_deathless_round_day = 49,
    ff_score_custom = 50,
    temp_f_2 = 51,
    temp_f_3 = 52,
    temp_f_4 = 53,
    temp_f_5 = 54,
}

export enum HaloReachMultiplayerChallenge {
    double_double_chall = 0,
    triple_double_chall = 1,
    quadruple_double_chal = 2,
    triple_kill_chall = 3,
    double_triple_chall = 4,
    mp_kill_spree_chall = 5,
    mp_kill_spree_2x_chall = 6,
    mp_kill_spree_3x_chall = 7,
    mp_frenzy_chall = 8,
    mp_riot_chall = 9,
    mp_3_multikill_chall = 10,
    mp_4_multikill_chall = 11,
    mp_headshot_3_chall = 12,
    mp_headshot_5_chall = 13,
    mp_headshot_10_chall = 14,
    mp_finish_move_chall = 15,
    mp_finish_move_2_chall = 16,
    mp_assist_5_chall = 17,
    mp_assist_10_chall = 18,
    mp_cqc_5_chall = 19,
    mp_cqc_7_chall = 20,
    mp_sticky_2_chall = 21,
    mp_sticky_4_chall = 22,
    mp_grenade_4_chall = 23,
    mp_grenade_8_chall = 24,
    mp_precision_5_chall = 25,
    mp_precision_10_chall = 26,
    mp_ordanance_5_chall = 27,
    mp_kill_9_chall = 28,
    mp_kill_10_chall = 29,
    mp_kill_17_chall = 30,
    mp_kill_20_chall = 31,
    mp_first_strike_chall = 32,
    mp_revenge_chall = 33,
    win_3_mm_games = 34,
    win_5_mm_games = 35,
    win_7_mm_games = 36,
    win_10_mm_games = 37,
    play_3_mm_games = 38,
    play_5_mm_games = 39,
    play_7_mm_games = 40,
    play_10_mm_games = 41,
    play_20_mm_games = 42,
    mp_multi_spree = 43,
    mp_multi_multikill = 44,
    mp_multi_precision = 45,
    mp_multi_auto = 46,
    mp_multi_small_arms = 47,
    mp_multi_cqc = 48,
    mp_open_nat_chall = 49,
    mp_linked_tag_chall = 50,
    mp_upload_film_chall = 51,
    armory_dress_chall = 52,
    mp_weekly_challenge = 53,
    mp_firebird_chall = 54,
    mp_avenger_chal = 55,
}

export const AVAILABLE_BOUNTY_CHALLENGES = [
    HaloReachBountyChallenge.any_100_kill_bounty,
    HaloReachBountyChallenge.any_50_kill_bounty,
    HaloReachBountyChallenge.any_25_kill_bounty,
    HaloReachBountyChallenge.mp_100_kill_bounty,
    HaloReachBountyChallenge.mp_50_kill_bounty,
    HaloReachBountyChallenge.mp_25_kill_bounty,
    HaloReachBountyChallenge.mp_50_assists_bounty,
    HaloReachBountyChallenge.mp_30_assists_bounty,
    HaloReachBountyChallenge.mp_20_assists_bounty,
    HaloReachBountyChallenge.mp_10_assists_bounty,
    HaloReachBountyChallenge.ff_100_kill_bounty,
    HaloReachBountyChallenge.ff_75_kill_bounty,
    HaloReachBountyChallenge.ff_50_kill_bounty,
    HaloReachBountyChallenge.ff_50_assists_bounty,
    HaloReachBountyChallenge.ff_30_assists_bounty,
    HaloReachBountyChallenge.ff_20_assists_bounty,
]

export const AVAILABLE_WEEKLY_CHALLENGES = [
    HaloReachWeeklyChallenge._30k_chall,
    HaloReachWeeklyChallenge.mp_spree_4x_chall_week,
    HaloReachWeeklyChallenge._1500k_week_chall,
    HaloReachWeeklyChallenge.win_50_mm_games,
    HaloReachWeeklyChallenge.win_77_mm_games,
    HaloReachWeeklyChallenge.m10_slaso,
    HaloReachWeeklyChallenge.m20_slaso,
    HaloReachWeeklyChallenge.m30_slaso,
    HaloReachWeeklyChallenge.m35_slaso,
    HaloReachWeeklyChallenge.m45_slaso,
    HaloReachWeeklyChallenge.m50_slaso,
    HaloReachWeeklyChallenge.m52_slaso,
    HaloReachWeeklyChallenge.m60_slaso,
    HaloReachWeeklyChallenge.m70_slaso,
    HaloReachWeeklyChallenge.weekly_open_nat_chall,
    HaloReachWeeklyChallenge.weekly_multikill_chall,
    HaloReachWeeklyChallenge.weekly_revenge_chall,
    HaloReachWeeklyChallenge.weekly_precision_chall,
    HaloReachWeeklyChallenge.play_x_mm_games,
    HaloReachWeeklyChallenge.m20_time_black_eye_chall,
    HaloReachWeeklyChallenge.endure_chall,
    HaloReachWeeklyChallenge.complete_all_daily_chall,
    HaloReachWeeklyChallenge.complete_x_daily_chall,
    HaloReachWeeklyChallenge.m30_sniper_weekly,
    HaloReachWeeklyChallenge.survival_round_weekly,
    HaloReachWeeklyChallenge.survival_wave_weekly,
    HaloReachWeeklyChallenge.legend_coop_weekly,
    HaloReachWeeklyChallenge.heroic_mission_weekly,
    HaloReachWeeklyChallenge.firebird_weekly_chall,
    HaloReachWeeklyChallenge.camp_any_speed_run,
    HaloReachWeeklyChallenge.camp_high_score,
    HaloReachWeeklyChallenge.legend_speed_solo_desc,
    // HaloReachWeeklyChallenge.temp_w_2,
    // HaloReachWeeklyChallenge.temp_w_3,
    // HaloReachWeeklyChallenge.temp_w_4,
    // HaloReachWeeklyChallenge.temp_w_5,
    // HaloReachWeeklyChallenge.temp_w_6,
    // HaloReachWeeklyChallenge.temp_w_7,
]

export const AVAILABLE_CAMPAIGN_CHALLENGES = [
    HaloReachCampaignChallenge.mythic_chall,
    HaloReachCampaignChallenge.tough_luck_chall,
    HaloReachCampaignChallenge.catch_chall,
    HaloReachCampaignChallenge.iron_solo_chall,
    HaloReachCampaignChallenge.famine_chall,
    HaloReachCampaignChallenge.thunderstorm_chall,
    HaloReachCampaignChallenge.iron_coop_chall,
    HaloReachCampaignChallenge.tilt_chall,
    HaloReachCampaignChallenge.mythic_luck_chall,
    HaloReachCampaignChallenge.mythic_storm_chall,
    HaloReachCampaignChallenge.mythic_tilt_storm_chall,
    HaloReachCampaignChallenge.storm_famine_tilt_chall,
    HaloReachCampaignChallenge.fog_catch_luck_chall,
    HaloReachCampaignChallenge.famine_luck_storm_chall,
    HaloReachCampaignChallenge.fog_famine_chall,
    HaloReachCampaignChallenge.mythic_tilt_storm_luck_chall,
    HaloReachCampaignChallenge.m10_l_deathless,
    HaloReachCampaignChallenge.m20_l_deathless,
    HaloReachCampaignChallenge.m30_l_deathless,
    HaloReachCampaignChallenge.m35_l_deathless,
    HaloReachCampaignChallenge.m45_l_deathless,
    HaloReachCampaignChallenge.m50_l_deathless,
    HaloReachCampaignChallenge.m52_l_deathless,
    HaloReachCampaignChallenge.m60_l_deathless,
    HaloReachCampaignChallenge.m70_l_deathless,
    HaloReachCampaignChallenge.any_score_easy_chall,
    HaloReachCampaignChallenge.m10_l_deathless_skull,
    HaloReachCampaignChallenge.m20_l_deathless_skull,
    HaloReachCampaignChallenge.m30_l_deathless_skull,
    HaloReachCampaignChallenge.m35_l_deathless_skull,
    HaloReachCampaignChallenge.m45_l_deathless_skull,
    HaloReachCampaignChallenge.m50_l_deathless_skull,
    HaloReachCampaignChallenge.m52_l_deathless_skull,
    HaloReachCampaignChallenge.m60_l_deathless_skull,
    HaloReachCampaignChallenge.m70_l_deathless_skull,
    HaloReachCampaignChallenge.elite_kill_chall,
    HaloReachCampaignChallenge.grunt_kill_chall,
    HaloReachCampaignChallenge.any_speed_chall,
    HaloReachCampaignChallenge.camp_precision_chall,
    HaloReachCampaignChallenge.camp_auto_chall,
    HaloReachCampaignChallenge.camp_leader_chall,
    HaloReachCampaignChallenge.camp_infantry_chall,
    HaloReachCampaignChallenge.m45_elite_pod_chall,
    HaloReachCampaignChallenge.single_skull_chall,
    HaloReachCampaignChallenge.special_elite_heroic,
    HaloReachCampaignChallenge.special_elite_normal,
    HaloReachCampaignChallenge.m30_sniper_chall,
    HaloReachCampaignChallenge.m30_sniper_med_chall,
    HaloReachCampaignChallenge.m20_airstrike_chall,
    HaloReachCampaignChallenge.m50_firebird_chall,
    HaloReachCampaignChallenge.fauna_kill_chall,
    HaloReachCampaignChallenge.score_constrained,
    HaloReachCampaignChallenge.score_deathless,
    HaloReachCampaignChallenge.special_elite_m52,
    // HaloReachCampaignChallenge.temp_c_5,
]

export const AVAILABLE_FIREFIGHT_CHALLENGES = [
    HaloReachFirefightChallenge.ff_kill_spree_chall,
    HaloReachFirefightChallenge.ff_kill_spree_5_chall,
    HaloReachFirefightChallenge.ff_h_kill_spree_10_chall,
    HaloReachFirefightChallenge.ff_multikill_7_chall,
    HaloReachFirefightChallenge.ff_h_multikill_7_chall,
    HaloReachFirefightChallenge.ff_grunt_kill_chall,
    HaloReachFirefightChallenge.ff_elite_kill_chall,
    HaloReachFirefightChallenge.ff_h_elite_kill_chall,
    HaloReachFirefightChallenge.ff_headshot_kill_chall,
    HaloReachFirefightChallenge.ff_launcher_kill_chall,
    HaloReachFirefightChallenge.ff_shotgun_kill_chall,
    HaloReachFirefightChallenge.ff_precision_kill_chall,
    HaloReachFirefightChallenge.ff_grenade_kill_chall,
    HaloReachFirefightChallenge.ff_pistol_chall,
    HaloReachFirefightChallenge.ff_supercombine_kill_chall,
    HaloReachFirefightChallenge.ff_sword_kill_chall,
    HaloReachFirefightChallenge.ff_overlook_kill_chall,
    HaloReachFirefightChallenge.ff_h_overlook_kill_chall,
    HaloReachFirefightChallenge.ff_l_overlook_kill_chall,
    HaloReachFirefightChallenge.ff_courtyard_kill_chall,
    HaloReachFirefightChallenge.ff_h_courtyard_kill_chall,
    HaloReachFirefightChallenge.ff_l_courtyard_kill_chall,
    HaloReachFirefightChallenge.ff_corvette_kill_chall,
    HaloReachFirefightChallenge.ff_h_corvette_kill_chall,
    HaloReachFirefightChallenge.ff_l_corvette_kill_chall,
    HaloReachFirefightChallenge.ff_holdout_kill_chall,
    HaloReachFirefightChallenge.ff_h_holdout_kill_chall,
    HaloReachFirefightChallenge.ff_l_holdout_kill_chall,
    HaloReachFirefightChallenge.ff_icecave_kill_chall,
    HaloReachFirefightChallenge.ff_h_icecave_kill_chall,
    HaloReachFirefightChallenge.ff_l_icecave_kill_chall,
    HaloReachFirefightChallenge.ff_park_kill_chall,
    HaloReachFirefightChallenge.ff_h_park_kill_chall,
    HaloReachFirefightChallenge.ff_l_park_kill_chall,
    HaloReachFirefightChallenge.ff_ruins_kill_chall,
    HaloReachFirefightChallenge.ff_h_ruins_kill_chall,
    HaloReachFirefightChallenge.ff_l_ruins_kill_chall,
    HaloReachFirefightChallenge.ff_easy_score_chall,
    HaloReachFirefightChallenge.ff_deathless_game_chall,
    HaloReachFirefightChallenge.ff_5_deaths_chall,
    HaloReachFirefightChallenge.ff_waterfront_kill_chall,
    HaloReachFirefightChallenge.ff_h_waterfront_kill_chall,
    HaloReachFirefightChallenge.ff_l_waterfront_kill_chall,
    HaloReachFirefightChallenge.kill_attack_chall,
    HaloReachFirefightChallenge.kill_h_attack_chall,
    HaloReachFirefightChallenge.vehicle_killing_chall,
    HaloReachFirefightChallenge.ff_airstrike_chall,
    HaloReachFirefightChallenge.ff_deathless_round,
    HaloReachFirefightChallenge.ff_deathless_rounds,
    HaloReachFirefightChallenge.ff_deathless_round_day,
    HaloReachFirefightChallenge.ff_score_custom,
    // HaloReachFirefightChallenge.temp_f_2,
    // HaloReachFirefightChallenge.temp_f_3,
    // HaloReachFirefightChallenge.temp_f_4,
    // HaloReachFirefightChallenge.temp_f_5,
]

export const AVAILABLE_MATCHMAKING_CHALELNGES = [
    HaloReachMultiplayerChallenge.double_double_chall,
    HaloReachMultiplayerChallenge.triple_double_chall,
    HaloReachMultiplayerChallenge.quadruple_double_chal,
    HaloReachMultiplayerChallenge.triple_kill_chall,
    HaloReachMultiplayerChallenge.double_triple_chall,
    HaloReachMultiplayerChallenge.mp_kill_spree_chall,
    HaloReachMultiplayerChallenge.mp_kill_spree_2x_chall,
    HaloReachMultiplayerChallenge.mp_kill_spree_3x_chall,
    HaloReachMultiplayerChallenge.mp_frenzy_chall,
    HaloReachMultiplayerChallenge.mp_riot_chall,
    HaloReachMultiplayerChallenge.mp_3_multikill_chall,
    HaloReachMultiplayerChallenge.mp_4_multikill_chall,
    HaloReachMultiplayerChallenge.mp_headshot_3_chall,
    HaloReachMultiplayerChallenge.mp_headshot_5_chall,
    HaloReachMultiplayerChallenge.mp_headshot_10_chall,
    HaloReachMultiplayerChallenge.mp_finish_move_chall,
    HaloReachMultiplayerChallenge.mp_finish_move_2_chall,
    HaloReachMultiplayerChallenge.mp_assist_5_chall,
    HaloReachMultiplayerChallenge.mp_assist_10_chall,
    HaloReachMultiplayerChallenge.mp_cqc_5_chall,
    HaloReachMultiplayerChallenge.mp_cqc_7_chall,
    HaloReachMultiplayerChallenge.mp_sticky_2_chall,
    HaloReachMultiplayerChallenge.mp_sticky_4_chall,
    HaloReachMultiplayerChallenge.mp_grenade_4_chall,
    HaloReachMultiplayerChallenge.mp_grenade_8_chall,
    HaloReachMultiplayerChallenge.mp_precision_5_chall,
    HaloReachMultiplayerChallenge.mp_precision_10_chall,
    HaloReachMultiplayerChallenge.mp_ordanance_5_chall,
    HaloReachMultiplayerChallenge.mp_kill_9_chall,
    HaloReachMultiplayerChallenge.mp_kill_10_chall,
    HaloReachMultiplayerChallenge.mp_kill_17_chall,
    HaloReachMultiplayerChallenge.mp_kill_20_chall,
    HaloReachMultiplayerChallenge.mp_first_strike_chall,
    HaloReachMultiplayerChallenge.mp_revenge_chall,
    HaloReachMultiplayerChallenge.win_3_mm_games,
    HaloReachMultiplayerChallenge.win_5_mm_games,
    HaloReachMultiplayerChallenge.win_7_mm_games,
    HaloReachMultiplayerChallenge.win_10_mm_games,
    HaloReachMultiplayerChallenge.play_3_mm_games,
    HaloReachMultiplayerChallenge.play_5_mm_games,
    HaloReachMultiplayerChallenge.play_7_mm_games,
    HaloReachMultiplayerChallenge.play_10_mm_games,
    HaloReachMultiplayerChallenge.play_20_mm_games,
    HaloReachMultiplayerChallenge.mp_multi_spree,
    HaloReachMultiplayerChallenge.mp_multi_multikill,
    HaloReachMultiplayerChallenge.mp_multi_precision,
    HaloReachMultiplayerChallenge.mp_multi_auto,
    HaloReachMultiplayerChallenge.mp_multi_small_arms,
    HaloReachMultiplayerChallenge.mp_multi_cqc,
    HaloReachMultiplayerChallenge.mp_open_nat_chall,
    // HaloReachMultiplayerChallenge.mp_linked_tag_chall, - Requires BNET signup, would be granted to all sunrise users currently.
    HaloReachMultiplayerChallenge.mp_upload_film_chall,
    HaloReachMultiplayerChallenge.armory_dress_chall,
    HaloReachMultiplayerChallenge.mp_weekly_challenge,
    HaloReachMultiplayerChallenge.mp_firebird_chall,
    HaloReachMultiplayerChallenge.mp_avenger_chal,
]