-- CreateTable
CREATE TABLE "halo3"."campaign_carnage_report" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "game_id" DECIMAL(20,0) NOT NULL,
    "map_id" INTEGER NOT NULL,
    "scenario_path" TEXT NOT NULL,
    "start_time" TIMESTAMP(6) NOT NULL,
    "finish_time" TIMESTAMP(6) NOT NULL,
    "language" INTEGER NOT NULL,
    "simulation" INTEGER NOT NULL,
    "network_type" INTEGER NOT NULL,
    "campaign_id" INTEGER NOT NULL,
    "campaign_difficulty" INTEGER NOT NULL,
    "campaign_insertion_point" INTEGER NOT NULL,
    "campaign_metagame_scoring" INTEGER NOT NULL,
    "campaign_metagame_enabled" BOOLEAN NOT NULL,
    "campaign_active_primary_skulls" INTEGER NOT NULL,
    "campaign_active_secondary_skulls" INTEGER NOT NULL,
    "total_elapsed_tick_count" INTEGER NOT NULL,
    "metagame_runtime_flags" INTEGER NOT NULL,
    "time_bonus" DOUBLE PRECISION NOT NULL,
    "final_total_score" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "campaign_carnage_report_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "halo3"."campaign_carnage_report_player" (
    "carnage_report_id" UUID NOT NULL,
    "player_identifier" DECIMAL(20,0) NOT NULL,
    "player_index" SMALLINT NOT NULL,
    "machine_index" SMALLINT,
    "player_name" VARCHAR(16) NOT NULL,
    "appearance_flags" INTEGER NOT NULL,
    "primary_color" INTEGER NOT NULL,
    "secondary_color" INTEGER NOT NULL,
    "tertiary_color" INTEGER NOT NULL,
    "player_model_choice" INTEGER NOT NULL,
    "foreground_emblem" INTEGER NOT NULL,
    "background_emblem" INTEGER NOT NULL,
    "emblem_flags" INTEGER NOT NULL,
    "emblem_primary_color" INTEGER NOT NULL,
    "emblem_secondary_color" INTEGER NOT NULL,
    "emblem_background_color" INTEGER NOT NULL,
    "spartan_model_area_0" INTEGER NOT NULL,
    "spartan_model_area_1" INTEGER NOT NULL,
    "spartan_model_area_2" INTEGER NOT NULL,
    "spartan_model_area_3" INTEGER NOT NULL,
    "elite_model_area_0" INTEGER NOT NULL,
    "elite_model_area_1" INTEGER NOT NULL,
    "elite_model_area_2" INTEGER NOT NULL,
    "elite_model_area_3" INTEGER NOT NULL,
    "service_tag" VARCHAR(4) NOT NULL,
    "player_xuid" DECIMAL(20,0) NOT NULL,
    "is_silver_or_gold_live" BOOLEAN NOT NULL,
    "is_online_enabled" BOOLEAN NOT NULL,
    "is_controller_attached" BOOLEAN NOT NULL,
    "user_selected_team_index" INTEGER NOT NULL,
    "desires_veto" BOOLEAN NOT NULL,
    "desires_rematch" BOOLEAN NOT NULL,
    "hopper_access_flags" INTEGER NOT NULL,
    "is_free_live_gold_account" BOOLEAN NOT NULL,
    "is_user_created_content_allowed" BOOLEAN NOT NULL,
    "is_friend_created_content_allowed" BOOLEAN NOT NULL,
    "is_griefer" SMALLINT NOT NULL,
    "campaign_difficulty_completed" INTEGER NOT NULL,
    "bungienet_user_flags" DECIMAL(20,0) NOT NULL,
    "gamer_region" INTEGER NOT NULL,
    "gamer_zone" INTEGER NOT NULL,
    "cheat_flags" DECIMAL(20,0) NOT NULL,
    "ban_flags" DECIMAL(20,0) NOT NULL,
    "repeated_play_coefficient" INTEGER NOT NULL,
    "experience_growth_banned" BOOLEAN NOT NULL,
    "matchmade_ranked_games_played" DECIMAL(20,0) NOT NULL,
    "matchmade_ranked_games_completed" DECIMAL(20,0) NOT NULL,
    "matchmade_ranked_games_won" DECIMAL(20,0) NOT NULL,
    "matchmade_unranked_games_played" DECIMAL(20,0) NOT NULL,
    "matchmade_unranked_games_completed" DECIMAL(20,0) NOT NULL,
    "hopper_experience_base" DECIMAL(20,0) NOT NULL,
    "custom_games_completed" DECIMAL(20,0) NOT NULL,
    "hopper_experience_penalty" DECIMAL(20,0) NOT NULL,
    "first_played" TIMESTAMP(6) NOT NULL,
    "last_played" TIMESTAMP(6) NOT NULL,
    "global_statistics_valid" SMALLINT NOT NULL,
    "global_statistics_highest_skill" DECIMAL(20,0) NOT NULL,
    "global_statistics_experience_base" DECIMAL(20,0) NOT NULL,
    "global_statistics_experience_penalty" DECIMAL(20,0) NOT NULL,
    "hopper_statistics_valid" SMALLINT NOT NULL,
    "hopper_statistics_identifier" INTEGER NOT NULL,
    "hopper_statistics_hopper_skill" DECIMAL(20,0) NOT NULL,
    "hopper_statistics_games_won" DECIMAL(20,0) NOT NULL,
    "hopper_statistics_games_played" DECIMAL(20,0) NOT NULL,
    "hopper_statistics_games_completed" DECIMAL(20,0) NOT NULL,
    "hopper_statistics_mu" DOUBLE PRECISION,
    "hopper_statistics_sigma" DOUBLE PRECISION,
    "player_team" INTEGER NOT NULL,
    "player_assigned_team" INTEGER NOT NULL,
    "host_stats_global_valid" BOOLEAN NOT NULL,
    "host_stats_global_experience" INTEGER NOT NULL,
    "host_stats_global_rank" INTEGER NOT NULL,
    "host_stats_global_grade" INTEGER NOT NULL,
    "host_stats_hopper_valid" BOOLEAN NOT NULL,
    "host_stats_hopper_skill" INTEGER NOT NULL,
    "host_stats_hopper_skill_display" INTEGER NOT NULL,
    "host_stats_hopper_skill_update_weight" INTEGER NOT NULL,
    "transient_subtotal" INTEGER NOT NULL,
    "subtotal" INTEGER NOT NULL,
    "medal_points" INTEGER NOT NULL,
    "scripted_points" INTEGER NOT NULL,
    "kill_counts" INTEGER NOT NULL,
    "grenade_sticky_kills" INTEGER NOT NULL,
    "headshot_kills" INTEGER NOT NULL,
    "assassination_kills" INTEGER NOT NULL,
    "splatter_kills" INTEGER NOT NULL,
    "multi_kills" INTEGER NOT NULL,
    "needler_supercombine_kills" INTEGER NOT NULL,
    "emp_kills" INTEGER NOT NULL,
    "ai_betrayal_count" INTEGER NOT NULL,
    "multikill_display_timer" INTEGER NOT NULL,
    "negative_toast_amount" INTEGER NOT NULL,
    "negative_toast_timer" INTEGER NOT NULL,
    "transient_scripted_points_amount" INTEGER NOT NULL,
    "transient_scripted_points_timer" INTEGER NOT NULL,
    "infantry_kills" INTEGER NOT NULL,
    "leader_kills" INTEGER NOT NULL,
    "hero_kills" INTEGER NOT NULL,
    "specialist_kills" INTEGER NOT NULL,
    "light_vehicle_kills" INTEGER NOT NULL,
    "heavy_vehicle_kills" INTEGER NOT NULL,
    "giant_vehicle_kills" INTEGER NOT NULL,
    "standard_vehicle_kills" INTEGER NOT NULL,
    "kill_total_count" INTEGER NOT NULL,
    "style_total_count" INTEGER NOT NULL,
    "finalized" BOOLEAN NOT NULL,
    "player_final_score" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "campaign_carnage_report_player_pkey" PRIMARY KEY ("carnage_report_id","player_index")
);

-- CreateTable
CREATE TABLE "halo3"."campaign_carnage_report_player_kills" (
    "player_xuid" DECIMAL(20,0) NOT NULL,
    "carnage_report_id" UUID NOT NULL,
    "enemy_type" TEXT NOT NULL,
    "infantry" INTEGER NOT NULL,
    "leader" INTEGER NOT NULL,
    "hero" INTEGER NOT NULL,
    "specialist" INTEGER NOT NULL,
    "light_vehicle" INTEGER NOT NULL,
    "heavy_vehicle" INTEGER NOT NULL,
    "giant_vehicle" INTEGER NOT NULL,
    "standard_vehicle" INTEGER NOT NULL,
    "halo3_campaign_carnage_report_playerCarnage_report_id" UUID,
    "halo3_campaign_carnage_report_playerPlayer_index" SMALLINT
);

-- CreateIndex
CREATE UNIQUE INDEX "campaign_carnage_report_start_time_finish_time_game_id_key" ON "halo3"."campaign_carnage_report"("start_time", "finish_time", "game_id");

-- CreateIndex
CREATE INDEX "campaign_carnage_report_player_player_name_idx" ON "halo3"."campaign_carnage_report_player"("player_name");

-- CreateIndex
CREATE INDEX "campaign_carnage_report_player_player_xuid_idx" ON "halo3"."campaign_carnage_report_player"("player_xuid");

-- CreateIndex
CREATE UNIQUE INDEX "unique_player_carnage_report_enemy_type" ON "halo3"."campaign_carnage_report_player_kills"("player_xuid", "carnage_report_id", "enemy_type");

-- AddForeignKey
ALTER TABLE "halo3"."campaign_carnage_report_player_kills" ADD CONSTRAINT "campaign_carnage_report_player_kills_halo3_campaign_carnag_fkey" FOREIGN KEY ("halo3_campaign_carnage_report_playerCarnage_report_id", "halo3_campaign_carnage_report_playerPlayer_index") REFERENCES "halo3"."campaign_carnage_report_player"("carnage_report_id", "player_index") ON DELETE SET NULL ON UPDATE CASCADE;
